### ISSUE TITLE
zsh: command not found: xit

### ISSUE THREAD

**Issue by yang-ling** [jlipps/tmux-safekill#1]
I got this error when I use this plugin.
![xit](https://cloud.githubusercontent.com/assets/1992391/5552417/5086c0b8-8c38-11e4-9b91-db3d3c1c5127.png)

I have tried to fix it. In `safekill.sh`

```bash
elif [[ "$pane_proc" == "bash" ]] || [[ "$pane_proc" == "zsh" ]]; then
cmd='C-c "exit" Enter'
```

I changed it to

```bash
elif [[ "$pane_proc" == "bash" ]] || [[ "$pane_proc" == "zsh" ]]; then
cmd='C-c C-u "exit" Enter'
```

And everything goes well.

I also tried to change it to

```bash
elif [[ "$pane_proc" == "bash" ]] || [[ "$pane_proc" == "zsh" ]]; then
cmd='C-c " exit" Enter'
```

An extra space is added before `exit`. In this case, no error happens but I need execute *\<prefix\>C* twice to completely kill the session.
Currently I don't know the reason.

In one word, `cmd='C-c C-u "exit" Enter'` solves my problem. But I don't know whether it is an elegant solution.

My environment information:

* Archlinux
* Zsh 5.0.7
* byobu 5.74
* tmux 1.9a
* tmuxinator 0.6.8

**Comment by jhenriquez** [comment]
@yang-ling I don't know what the `C-u` does but I don't think that is necessary. If you're already on `bash` (in my case) you only need to type `exit`.

If your terminal needs any special inputs for exiting, I would probably add a separate if for it.

@jlipps I was experiencing this same problem out of the box (having to run the command multiple times), is there a particular reason to try C-c before typing exit on the shell?

This is how my modified version looks right now and it's working beatifully! Also, thanks @jlipps this is great!

```bash
function safe_end_procs {
    old_ifs="$IFS"
    IFS=$'\n'
    panes=$(tmux list-panes -s -F "#{pane_id} #{pane_current_command}")
    for pane_set in $panes; do
        pane_id=$(echo "$pane_set" | awk -F " " '{print $1}')
        pane_proc=$(echo "$pane_set" | awk -F " " '{print tolower($2)}')
        cmd="C-c"
        if [[ "$pane_proc" == "vim" ]]; then
            cmd='":qa" Enter'
        elif [[ "$pane_proc" == "man" ]] || [[ "$pane_proc" == "less" ]]; then
            cmd='"q"'
        elif [[ "$pane_proc" == "bash" ]] || [[ "$pane_proc" == "zsh" ]] || [[ "$pane_proc" == "fish" ]]; then
            cmd='"exit" Enter'
        elif [[ "$pane_proc" == "ssh" ]]; then
            cmd='Enter "~."'
        fi
        echo $cmd | xargs tmux send-keys -t "$pane_id"
    done
    IFS="$old_ifs"
}
```

**Comment by yang-ling** [comment]
@jhenriquez `C-u` clears the command line. It has no side effect and can make sure the command line is empty before typing `exit`

**Comment by jhenriquez** [comment]
Oh! It makes sense now. I still don't think the C-c is needed if I'm
following the script along. It's working fine for me without it, though.
There might be cases I assume :)

Thanks @SpicyCat !

**Comment by jlipps** [comment]
I'd merge this as a PR @yang-ling! Agree with @jhenriquez I'm not sure if we still need the "C-c" (maybe I was being overly protective?) but there may have been a good reason it's there so I'm fine keeping it.
