### ISSUE TITLE
Does this kill the actual session?

### ISSUE THREAD

**Issue by sam-k** [jlipps/tmux-safekill#16]
Reading the script, this seems to kill only the processes in each pane. Am I correct in understanding this script doesn't kill the actual session itself (`tmux kill-session`)?

(Also: why is `safe_kill_panes_of_current_session` called twice?)

**Comment by jlipps** [comment]
It kills the session by exiting all the panes in it. When you do that, the session ends.

> (Also: why is safe_kill_panes_of_current_session called twice?)

I'm not entirely sure, I guess just as an umbrella retry in case something didn't work the first time around. This change was added in https://github.com/jlipps/tmux-safekill/commit/5c881010ae2fef912fc5288ebf0e2a7924456462, so maybe @lo-tp  can comment on the reason for the duplication there.

**Comment by sam-k** [comment]
If you send Ctrl-C to a pane, that doesn't necessarily exit the pane, right? The pane closes only if it was initialized with a command.

**Comment by jlipps** [comment]
no, that's why we run `exit` as well once any processes have been killed (at best attempt).

**Comment by lo-tp** [comment]
Some apps cannot be killed by the first attempt so I added the second try to ensure a successful exit.
